import type { Metadata } from "next";
import { AdminActionButton } from "@/components/admin/admin-action-button";
import { AdminButton, AdminField, AdminPageHeader, AdminStatusBadge } from "@/components/admin/admin-ui";
import { AdminMutationForm } from "@/components/admin/admin-mutation-form";
import { requireAdminPagePermission } from "@/lib/admin/page";
import { getAdminCourse } from "@/lib/admin/courses";

export const metadata: Metadata = { title: "ویرایش درس" };
export default async function LessonDetailPage({ params }: { params: Promise<{ id: string; moduleId: string; lessonId: string }> }) { const session = await requireAdminPagePermission("lessons.write"); const { id, moduleId, lessonId } = await params; const course = await getAdminCourse(id, session); const courseModule = course.course.modules.find((item) => item.id === moduleId); const lesson = courseModule?.lessons.find((item) => item.id === lessonId); if (!lesson) return <div className="admin-page-stack"><AdminButton href={`/admin/courses/${id}/modules/${moduleId}`} variant="secondary">بازگشت</AdminButton></div>; const statusAction = lesson.status === "PUBLISHED" ? { status: "DRAFT", label: "لغو انتشار", variant: "secondary" as const } : lesson.status === "ARCHIVED" ? { status: "DRAFT", label: "بازگردانی", variant: "secondary" as const } : { status: "PUBLISHED", label: "انتشار", variant: "primary" as const }; return <div className="admin-page-stack"><AdminPageHeader eyebrow="Lesson" title={lesson.title} action={<AdminButton href={`/admin/courses/${id}/modules/${moduleId}`} variant="secondary">بازگشت به ماژول</AdminButton>} /><section className="admin-panel-card"><div className="admin-section-heading"><h3>اطلاعات درس</h3><AdminStatusBadge tone={lesson.status === "PUBLISHED" ? "success" : lesson.status === "ARCHIVED" ? "neutral" : "warning"}>{lesson.status}</AdminStatusBadge></div><AdminMutationForm action={`/api/admin/courses/lessons/${lesson.id}`} method="PATCH"><AdminField label="عنوان" name="title" defaultValue={lesson.title} required /><label className="admin-form-field"><span>توضیحات</span><textarea name="description" defaultValue={lesson.description ?? ""} /></label><AdminField label="مدت به دقیقه" name="duration" type="number" defaultValue={lesson.duration ?? ""} /><label className="admin-form-field"><span><input name="isPreview" type="checkbox" value="true" defaultChecked={lesson.isPreview} /> پیش‌نمایش رایگان</span></label></AdminMutationForm><div className="admin-form-actions"><AdminActionButton action={`/api/admin/courses/lessons/${lesson.id}`} method="PATCH" body={{ status: statusAction.status }} reasonRequired label={statusAction.label} variant={statusAction.variant} confirm="وضعیت درس تغییر کند؟" />{lesson.status !== "ARCHIVED" ? <AdminActionButton action={`/api/admin/courses/lessons/${lesson.id}`} method="PATCH" body={{ status: "ARCHIVED" }} reasonRequired label="بایگانی" variant="danger" confirm="این درس بایگانی شود؟" /> : null}</div></section></div>; }
