import type { Metadata } from "next";
import { AdminActionButton } from "@/components/admin/admin-action-button";
import { AdminButton, AdminPageHeader, AdminStatusBadge } from "@/components/admin/admin-ui";
import { AdminIndividualConsultationForm } from "@/components/admin/admin-therapy-product-forms";
import { requireAdminPagePermission } from "@/lib/admin/page";
import { getAdminTherapyProduct } from "@/lib/admin/therapy-products";
import { ProductStatus } from "@/lib/generated/prisma/enums";

export const metadata: Metadata = { title: "جزئیات مشاوره فردی" };
function statusLabel(status: ProductStatus) { return status === ProductStatus.PUBLISHED ? "منتشرشده" : status === ProductStatus.ARCHIVED ? "مخفی‌شده" : "پیش‌نویس"; }

export default async function IndividualConsultationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAdminPagePermission("products.read"); const { id } = await params; const product = await getAdminTherapyProduct("consultation", id); const canWrite = session.permissions.includes("products.write"); const statusAction = product.status === ProductStatus.PUBLISHED ? { status: ProductStatus.ARCHIVED, label: "مخفی کردن", variant: "danger" as const, confirm: "این مشاوره فردی از سایت مخفی شود؟" } : product.status === ProductStatus.ARCHIVED ? { status: ProductStatus.DRAFT, label: "نمایش دوباره", variant: "secondary" as const, confirm: "این مشاوره فردی دوباره به پیش‌نویس برگردد؟" } : { status: ProductStatus.PUBLISHED, label: "انتشار", variant: "primary" as const, confirm: "این مشاوره فردی در سایت منتشر شود؟" };
  return <div className="admin-page-stack"><AdminPageHeader eyebrow="Consultation / ConsultationProduct" title={product.title} description={`وضعیت فعلی: ${statusLabel(product.status)}`} action={<AdminButton href="/individual-consultation" variant="secondary">بازگشت به مشاوره فردی</AdminButton>} /><section className="admin-panel-card admin-course-create-card"><div className="admin-section-heading"><h3>ویرایش مشاوره فردی</h3><AdminStatusBadge tone={product.status === ProductStatus.PUBLISHED ? "success" : product.status === ProductStatus.DRAFT ? "warning" : "neutral"}>{statusLabel(product.status)}</AdminStatusBadge></div>{canWrite ? <AdminIndividualConsultationForm productId={product.id} values={{ ...product, discountPercent: product.discountPercent, durationMinutes: product.consultation?.durationMinutes ?? 50, includedSessions: product.sessionPackage?.includedSessions ?? 1 }} /> : <dl className="admin-detail-list"><div><dt>Slug</dt><dd dir="ltr">{product.slug}</dd></div><div><dt>توضیحات</dt><dd className="admin-course-description">{product.description}</dd></div><div><dt>قیمت</dt><dd dir="ltr">{(product.priceMinor / 100).toLocaleString("fa-IR")} {product.currency}</dd></div></dl>}{canWrite ? <div className="admin-form-actions"><AdminActionButton action={`/api/admin/individual-consultation/${product.id}/status`} method="PATCH" body={{ status: statusAction.status, ...(statusAction.status === ProductStatus.PUBLISHED ? { reason: "انتشار مشاوره فردی" } : {}) }} label={statusAction.label} variant={statusAction.variant} reasonRequired={statusAction.status !== ProductStatus.PUBLISHED} confirm={statusAction.status === ProductStatus.PUBLISHED ? undefined : statusAction.confirm} successMessage={statusAction.status === ProductStatus.PUBLISHED ? "مشاوره فردی منتشر شد و در سایت نمایش داده می‌شود." : `وضعیت مشاوره فردی به «${statusAction.label}» تغییر کرد.`} /><AdminActionButton action={`/api/admin/individual-consultation/${product.id}`} method="DELETE" label="حذف مشاوره فردی" variant="danger" confirm="این مشاوره فردی برای همیشه حذف شود؟ اگر سابقه خرید یا جلسه داشته باشد حذف انجام نمی‌شود." successMessage="مشاوره فردی حذف شد." /></div> : null}</section></div>;
}
