import type { Metadata } from "next";
import Link from "next/link";
import { AdminActionButton } from "@/components/admin/admin-action-button";
import { AdminSelect } from "@/components/admin/admin-select";
import { AdminButton, AdminDataTable, AdminEmptyState, AdminListToolbar, AdminPageHeader, AdminPagination, AdminSearchInput, AdminStatusBadge } from "@/components/admin/admin-ui";
import { listAdminCategories } from "@/lib/admin/categories";
import { requireAdminPagePermission } from "@/lib/admin/page";
import { parseAdminListQuery } from "@/lib/admin/query";
import { CategoryStatus } from "@/lib/generated/prisma/enums";

export const metadata: Metadata = { title: "دسته‌بندی‌ها" };
const labels: Record<CategoryStatus, string> = { ACTIVE: "فعال", ARCHIVED: "بایگانی" };

export default async function CategoriesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const session = await requireAdminPagePermission("categories.read"); const params = await searchParams; const query = parseAdminListQuery(params, ["updatedAt", "title"]); const value = typeof params.status === "string" ? params.status : Array.isArray(params.status) ? params.status[0] : undefined; const status = Object.values(CategoryStatus).includes(value as CategoryStatus) ? value as CategoryStatus : undefined; const data = await listAdminCategories(query, status); const canWrite = session.permissions.includes("categories.write"); const currentParams = Object.fromEntries(Object.entries(params).map(([key, item]) => [key, Array.isArray(item) ? item[0] : item])); return <div className="admin-page-stack"><AdminPageHeader title="دسته‌بندی‌ها" description="دسته‌بندی‌های مرتبط با کاتالوگ واقعی محصولات." action={canWrite ? <AdminButton href="/categories/new">دسته‌بندی جدید</AdminButton> : undefined} /><section className="admin-panel-card"><AdminListToolbar><AdminSearchInput defaultValue={query.search} placeholder="عنوان یا slug" /><label className="admin-search-field"><span>وضعیت</span><AdminSelect name="status" defaultValue={status ?? ""} ariaLabel="وضعیت دسته‌بندی" options={[{ value: "", label: "همه" }, { value: "ACTIVE", label: "فعال" }, { value: "ARCHIVED", label: "بایگانی" }]} /></label><input type="hidden" name="sort" value={query.sort} /></AdminListToolbar>{data.rows.length ? <AdminDataTable rows={data.rows} getRowKey={(row) => row.id} columns={[{ key: "title", label: "عنوان", render: (row) => <Link className="admin-table-link" href={`/categories/${row.id}`}>{row.title}</Link> }, { key: "slug", label: "Slug", render: (row) => <span dir="ltr">{row.slug}</span> }, { key: "status", label: "وضعیت", render: (row) => <AdminStatusBadge tone={row.status === CategoryStatus.ACTIVE ? "success" : "neutral"}>{labels[row.status]}</AdminStatusBadge> }, { key: "products", label: "محصولات", render: (row) => <span>{row._count.products.toLocaleString("fa-IR")}</span> }, ...(canWrite ? [{ key: "actions", label: "عملیات", render: (row: (typeof data.rows)[number]) => row.status === CategoryStatus.ACTIVE ? <AdminActionButton action={`/api/admin/categories/${row.id}/status`} method="PATCH" body={{ status: "ARCHIVED" }} reasonRequired label="بایگانی" variant="danger" /> : <AdminActionButton action={`/api/admin/categories/${row.id}/status`} method="PATCH" body={{ status: "ACTIVE" }} reasonRequired label="بازگردانی" /> }] : [])]} /> : <AdminEmptyState title="دسته‌بندی‌ای پیدا نشد" action={canWrite ? <AdminButton href="/categories/new">دسته‌بندی جدید</AdminButton> : undefined} />}<AdminPagination page={data.meta.page} pageCount={data.meta.pageCount} searchParams={currentParams} /></section></div>; }
