import type { Metadata } from "next";
import { AdminSelect } from "@/components/admin/admin-select";
import { AdminDataTable, AdminEmptyState, AdminListToolbar, AdminPageHeader, AdminPagination, AdminSearchInput, AdminStatusBadge } from "@/components/admin/admin-ui";
import { listAdminOrders } from "@/lib/admin/orders";
import { requireAdminPagePermission } from "@/lib/admin/page";
import { parseAdminListQuery } from "@/lib/admin/query";
import { OrderStatus } from "@/lib/generated/prisma/enums";

export const metadata: Metadata = { title: "سفارش‌ها" };
const labels: Record<OrderStatus, string> = { PENDING: "در انتظار", AWAITING_PAYMENT: "در انتظار پرداخت", PAID: "پرداخت‌شده", FAILED: "ناموفق", CANCELED: "لغوشده", EXPIRED: "منقضی", REFUNDED: "بازپرداخت‌شده" };
export default async function OrdersPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { await requireAdminPagePermission("orders.read"); const params = await searchParams; const query = parseAdminListQuery(params, ["createdAt", "status", "totalMinor"]); const value = typeof params.status === "string" ? params.status : undefined; const status = Object.values(OrderStatus).includes(value as OrderStatus) ? value as OrderStatus : undefined; const data = await listAdminOrders(query, status); const currentParams = Object.fromEntries(Object.entries(params).map(([key, item]) => [key, Array.isArray(item) ? item[0] : item])); return <div className="admin-page-stack"><AdminPageHeader eyebrow="فقط خواندنی" title="سفارش‌ها" description="اطلاعات سفارش‌ها و پرداخت‌ها بدون عملیات مالی از اینجا قابل مشاهده است." /><section className="admin-panel-card"><AdminListToolbar><AdminSearchInput defaultValue={query.search} placeholder="شماره سفارش، ایمیل یا محصول" /><label className="admin-search-field"><span>وضعیت</span><AdminSelect name="status" defaultValue={status ?? ""} ariaLabel="وضعیت سفارش" options={[{ value: "", label: "همه" }, ...Object.values(OrderStatus).map((item) => ({ value: item, label: labels[item] }))]} /></label><input type="hidden" name="sort" value={query.sort} /></AdminListToolbar>{data.rows.length ? <AdminDataTable rows={data.rows} getRowKey={(row) => row.id} columns={[{ key: "order", label: "شماره سفارش", render: (row) => <span dir="ltr">{row.orderNumber}</span> }, { key: "user", label: "کاربر", render: (row) => <span dir="ltr">{row.user.email}</span> }, { key: "product", label: "محصول", render: (row) => <span>{row.productTitleSnapshot}</span> }, { key: "amount", label: "مبلغ", render: (row) => <span dir="ltr">{(row.totalMinor / 100).toFixed(2)} {row.currency}</span> }, { key: "status", label: "وضعیت", render: (row) => <AdminStatusBadge tone={row.status === OrderStatus.PAID ? "success" : row.status === OrderStatus.FAILED ? "danger" : "neutral"}>{labels[row.status]}</AdminStatusBadge> }, { key: "payment", label: "درگاه", render: (row) => <span dir="ltr">{row.payments[0]?.provider ?? "—"}</span> }]} /> : <AdminEmptyState title="سفارشی پیدا نشد" description="سفارش‌های canonical سیستم در اینجا نمایش داده می‌شوند." />}<AdminPagination page={query.page} pageCount={data.meta.pageCount} searchParams={currentParams} /></section></div>; }
