import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AdminActionButton } from "@/components/admin/admin-action-button";
import { AdminButton, AdminPageHeader, AdminStatusBadge } from "@/components/admin/admin-ui";
import { AdminCategoryForm } from "@/components/admin/admin-category-form";
import { getAdminCategory } from "@/lib/admin/categories";
import { requireAdminPagePermission } from "@/lib/admin/page";
import { CategoryStatus } from "@/lib/generated/prisma/enums";
export const metadata: Metadata = { title: "ویرایش دسته‌بندی" };
export default async function CategoryDetailPage({ params }: { params: Promise<{ id: string }> }) { const session = await requireAdminPagePermission("categories.read"); let category; try { category = await getAdminCategory((await params).id); } catch { notFound(); } const canWrite = session.permissions.includes("categories.write"); const target = category.status === CategoryStatus.ACTIVE ? CategoryStatus.ARCHIVED : CategoryStatus.ACTIVE; return <div className="admin-page-stack"><AdminPageHeader title="ویرایش دسته‌بندی" action={<AdminButton href="/categories" variant="secondary">بازگشت</AdminButton>} /><section className="admin-panel-card"><AdminStatusBadge tone={category.status === CategoryStatus.ACTIVE ? "success" : "neutral"}>{category.status}</AdminStatusBadge>{canWrite ? <AdminCategoryForm action={`/api/admin/categories/${category.id}`} method="PATCH" values={category} /> : <dl className="admin-detail-list"><div><dt>عنوان</dt><dd>{category.title}</dd></div><div><dt>Slug</dt><dd dir="ltr">{category.slug}</dd></div><div><dt>توضیح</dt><dd>{category.description || "—"}</dd></div></dl>}{canWrite && category._count.products === 0 ? <div className="admin-form-actions"><AdminActionButton action={`/api/admin/categories/${category.id}/status`} method="PATCH" body={{ status: target }} reasonRequired label={target === CategoryStatus.ARCHIVED ? "بایگانی" : "بازگردانی"} variant={target === CategoryStatus.ARCHIVED ? "danger" : "primary"} /></div> : canWrite ? <p className="admin-form-hint">این دسته‌بندی به {category._count.products.toLocaleString("fa-IR")} محصول متصل است و حذف نمی‌شود؛ در صورت نیاز آن را بایگانی کنید.</p> : null}</section></div>; }
