import type { Metadata } from "next";
import { AdminActionButton } from "@/components/admin/admin-action-button";
import { AdminSelect } from "@/components/admin/admin-select";
import { AdminDataTable, AdminEmptyState, AdminListToolbar, AdminPageHeader, AdminPagination, AdminSearchInput, AdminStatusBadge } from "@/components/admin/admin-ui";
import { requireAdminPagePermission } from "@/lib/admin/page";
import { listAdminReviews, type AdminReviewStatus } from "@/lib/admin/reviews";
import { parseAdminListQuery } from "@/lib/admin/query";
import { ReviewStatus } from "@/lib/generated/prisma/enums";

export const metadata: Metadata = { title: "نظرات" };
const statusLabel: Record<AdminReviewStatus, string> = { PENDING: "در انتظار بررسی", PUBLISHED: "منتشرشده", HIDDEN: "پنهان‌شده", USER_DELETED: "حذف توسط کاربر" };
const adminReviewStatusValues: AdminReviewStatus[] = [...Object.values(ReviewStatus), "USER_DELETED"];
function tone(status: AdminReviewStatus) { return status === ReviewStatus.PUBLISHED ? "success" : status === ReviewStatus.HIDDEN ? "neutral" : status === "USER_DELETED" ? "danger" : "warning"; }

export default async function ReviewsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireAdminPagePermission("reviews.read"); const params = await searchParams; const query = parseAdminListQuery(params, ["createdAt", "status", "rating"]); const value = typeof params.status === "string" ? params.status : Array.isArray(params.status) ? params.status[0] : undefined; const status = adminReviewStatusValues.includes(value as AdminReviewStatus) ? value as AdminReviewStatus : undefined; const data = await listAdminReviews(query, status); const currentParams = Object.fromEntries(Object.entries(params).map(([key, item]) => [key, Array.isArray(item) ? item[0] : item])); const canModerate = session.permissions.includes("reviews.moderate");
  return <div className="admin-page-stack"><AdminPageHeader eyebrow="Review moderation" title="نظرات" description="مدیریت وضعیت نظرات واقعی ثبت‌شده در سیستم؛ حذف فیزیکی انجام نمی‌شود." /><section className="admin-panel-card admin-reviews-panel"><AdminListToolbar><AdminSearchInput defaultValue={query.search} placeholder="متن نظر، کاربر یا محصول" /><label className="admin-search-field"><span>وضعیت</span><AdminSelect name="status" defaultValue={status ?? ""} ariaLabel="وضعیت نظر" options={[{ value: "", label: "همه" }, ...adminReviewStatusValues.map((item) => ({ value: item, label: statusLabel[item] }))]} /></label><input type="hidden" name="sort" value={query.sort} /></AdminListToolbar>{data.rows.length ? <AdminDataTable rows={data.rows} getRowKey={(row) => row.id} columns={[{ key: "body", label: "متن نظر", className: "admin-review-body-column", render: (row) => <span className="admin-clamp-text" title={row.body}>{row.body}</span> }, { key: "user", label: "کاربر", render: (row) => { const name = row.user.profile?.displayName || row.user.email; return <span className="admin-review-user-cell">{name}</span>; } }, { key: "product", label: "محصول", render: (row) => <span className="admin-review-product-cell">{row.product?.title || "—"}</span> }, { key: "status", label: "وضعیت", render: (row) => <span className="admin-review-status-cell"><AdminStatusBadge tone={tone(row.status)}>{statusLabel[row.status]}</AdminStatusBadge></span> }, { key: "date", label: "تاریخ", render: (row) => <time className="admin-review-date-cell" dateTime={row.createdAt.toISOString()}>{row.createdAt.toLocaleDateString("fa-IR")}</time> }, ...(canModerate ? [{ key: "actions", label: "عملیات", render: (row: (typeof data.rows)[number]) => <span className="admin-form-actions admin-table-actions">{row.status !== ReviewStatus.PUBLISHED && row.status !== "USER_DELETED" ? <span className="admin-review-action-publish"><AdminActionButton action={`/api/admin/reviews/${row.id}/status`} method="PATCH" body={{ status: "PUBLISHED" }} label="انتشار" variant="primary" successMessage="نظر با موفقیت منتشر شد." /></span> : null}{row.status !== ReviewStatus.HIDDEN && row.status !== "USER_DELETED" ? <span className="admin-review-action-hide"><AdminActionButton action={`/api/admin/reviews/${row.id}/status`} method="PATCH" body={{ status: "HIDDEN" }} label="پنهان‌کردن" variant="danger" successMessage="نظر با موفقیت پنهان شد." /></span> : null}</span> }] : [])]} /> : <AdminEmptyState title="نظری پیدا نشد" description="فیلتر یا عبارت جست‌وجو را تغییر دهید." />}<AdminPagination page={query.page} pageCount={data.meta.pageCount} searchParams={currentParams} /></section></div>;
}
