import type { Metadata } from "next";
import { AdminButton, AdminDataTable, AdminPageHeader } from "@/components/admin/admin-ui";
import { AdminMutationForm } from "@/components/admin/admin-mutation-form";
import { AdminField } from "@/components/admin/admin-ui";
import { requireAdminPagePermission } from "@/lib/admin/page";
import { getAdminCourse } from "@/lib/admin/courses";

export const metadata: Metadata = { title: "ساختار دوره" };
export default async function CourseModulesPage({ params }: { params: Promise<{ id: string }> }) { const session = await requireAdminPagePermission("lessons.read"); const { id } = await params; const course = await getAdminCourse(id, session); const canWrite = session.permissions.includes("lessons.write"); return <div className="admin-page-stack"><AdminPageHeader eyebrow="ساختار آموزشی" title={course.title} action={<AdminButton href={`/admin/courses/${id}`} variant="secondary">بازگشت به دوره</AdminButton>} />{canWrite ? <section className="admin-panel-card"><h3>افزودن ماژول</h3><AdminMutationForm action={`/api/admin/courses/${id}/modules`}><AdminField label="عنوان ماژول" name="title" required /><label className="admin-form-field"><span>توضیحات</span><textarea name="description" /></label></AdminMutationForm></section> : null}{course.course.modules.map((module) => <section className="admin-panel-card" key={module.id}><div className="admin-section-heading"><h3>{(module.order + 1).toLocaleString("fa-IR")} — {module.title}</h3>{canWrite ? <AdminButton href={`/admin/courses/${id}/modules/${module.id}`} variant="secondary">جزئیات ماژول</AdminButton> : null}</div><AdminDataTable rows={module.lessons} getRowKey={(row) => row.id} columns={[{ key: "order", label: "ترتیب", render: (row) => <span>{(row.order + 1).toLocaleString("fa-IR")}</span> }, { key: "title", label: "عنوان درس", render: (row) => <span>{row.title}</span> }, { key: "preview", label: "پیش‌نمایش", render: (row) => <span>{row.isPreview ? "رایگان" : "قفل"}</span> }]} empty={<p className="admin-table-empty">درسی ثبت نشده است.</p>} /></section>)}</div>; }
